#!/usr/bin/env bash

ERROR_INVALID_ARGUMENTS=1
ERROR_UNKNOWN_APP=2
ERROR_UNKNOWN_OPERATOR=3
ERROR_NO_ENV=4

this="$0"
app="$1"
op="$2"

usage() {
  echo -e "${this} <app> <operator>"
  echo -e "\tapp"
  echo -e "\t\tpostgres: Postgresql"
  echo -e "\toperator"
  echo -e "\t\tps: Status of app"
  echo -e "\t\tup: Start docker app"
  echo -e "\t\tdown: Stop docker app"
  echo -e "\t\trestart: Stop and Start docker app"
}

[[ $# -ne 2 ]] && usage && exit ${ERROR_INVALID_ARGUMENTS}

[[ ! -d "./${app}" ]] && echo "Unknown app ${app}" && exit ${ERROR_UNKNOWN_APP}

case ${op} in
  ps|up|down|restart)
    ;;
  *)
    echo "Unknown operator ${op}"
    exit ${ERROR_UNKNOWN_OPERATOR}
    ;;
esac

pushd "./${app}"
[[ ! -f ".env" ]] && echo "No .env found in `pwd`" && popd && exit ${ERROR_NO_ENV}
case ${op} in
  ps)
    docker compose ps
    ;;
  up)
    docker compose up -d
    ;;
  down)
    docker compose down
    ;;
  restart)
    docker compose down && docker compose up -d
    ;;
  *)
    echo "Unknown operator ${op}"
    exit ${ERROR_UNKNOWN_OPERATOR}
    ;;
esac
popd
