version: '3'
services:
  nginx:
    container_name: flp-nginx
    image: nginx:${IMAGE_TAG:?IMAGE_TAG}
    restart: always
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:?LOG_MAX_SIZE:?LOG_MAX_SIZE}
    ports:
      - ${PORT_HTTP:?PORT_HTTP}:80
      - ${PORT_HTTPS:?PORT_HTTPS}:443
    volumes:
      - ${VOLUMES_BASE:?VOLUMES_BASE}/conf.d:/etc/nginx/conf.d
      - ${VOLUMES_BASE:?VOLUMES_BASE}/certs:/etc/certs
