version: '3'
services:
  postgres:
    container_name: flp-postgres
    image: postgres:${IMAGE_TAG:?IMAGE_TAG}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${PASSWORD:?PASSWORD}
    logging:
      driver: json-file
      options:
        max-size: ${LOG_MAX_SIZE:?LOG_MAX_SIZE}
    ports:
      - ${PORT:?PORT}:5432
    volumes:
      - ${VOLUMES_BASE:?VOLUMES_BASE}/data:/var/lib/postgresql/data
